name : Build and release
on:
    push:
        tags:
            - 'v*'

permissions:
    contents: write
jobs:
    release:
        runs-on: windows-latest

        steps:
            - name: Checkout reopsitory
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: 'npm'

            - name: install dependencies
              run: npm ci

            - name: Build and publish
              run: npx electron-builder --win --publish always --draft false
              env: 
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            

            